console.log("KSI VS TOMMY FURY NEGOTIATIONS CLOSE TO BEING DONE AND THE WEIGHT HAS BEEN AGREED ON WHICH IS 183LBS")






console.log("THE UNDERCARD IS STACKED CO-MAIN IS SLIM VS BLUEFACE FOR THE MF LIGHT HEAVYWEIGHT TITLE")